spring:
  application:
    name: cleanarch
  mongodb:
    uri: mongodb://root:example@localhost:27017/cleanarch?authSource=admin

paschoalick:
  client:
    address:
      url: http://localhost:8082/address

